language: csharp
solution: WebServiceCSharp.sln
script:
  - xbuild /p:Configuration=Release WebServiceCSharp.sln
  - mono ./packages/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./WebServiceCSharpTests/bin/Release/WebServiceCSharpTests.dll
deploy:
  provider: releases
  user: "allforme3"
  password: "liverpool10"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true