language: csharp
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore WebServiceCSharp.sln
after_script:
  - nunit-console WebServiceCSharpTests/bin/Debug/WebServiceCSharpTests.dll