Open Source XML & JSON Visualisation Software: WebServer.Program Class Reference
WebServer.Program Class Reference
The Initialiser
Static Private Member Functions
static void Main (string[] args)
The Main function that starts the HttpServer
Detailed Description
The Initialiser
Definition at line 12 of file Program.cs.
Member Function Documentation
Main()
static void WebServer.Program.Main (string [] args) static private
The Main function that starts the HttpServer
Parameters
args Pass Cache Folder and Logger (Optional)
Definition at line 18 of file Program.cs.
References OSXJV.Classes.CacheManager.Setup(), OSXJV.Classes.Logger.Setup(), and OSXJV.Server.OSXJVServer.Start().
         {
             if (args.Length == 0)
             {
                 Console.WriteLine("Using Default Cache Directory Path and Logger Directory Path");
                 string dir = Directory.GetCurrentDirectory();
                 Array.Resize(ref args, 2);
                 args[0] = dir + "/Cache/";
                 args[1] = dir + "/Logger/";
                 if (!Directory.Exists(args[0]))
                     Directory.CreateDirectory(args[0]);
                 if (!Directory.Exists(args[1]))
                     Directory.CreateDirectory(args[1]);
             }
             if (args[0] == args[1])
             {
                 Console.WriteLine("Cache location and Log location is the same. Please enter two different locations");
             }
             else
             {
                 bool pass = false;
                 try
                 {
                     pass = CacheManager.Setup(args[0]);
                     pass = Logger.Setup(args[1]);
                 }
                 catch (Exception e)
                 {
                     Console.WriteLine("Error Setting Cache and Logger Directory: {0}", e.Message);
                 }
                 if (pass)
                 {
                     OSXJVServer s = new OSXJVServer();
                     s.Start();
                 }
                 //Check Cache every hour to remove old files
                 while (true)
                 {
                     Thread.Sleep(3600000);
                     string[] files = Directory.GetFiles(args[0]);
                     foreach (string file in files)
                     {
                         if (File.GetLastAccessTime(file) < DateTime.Now.AddHours(-6.0))
                             File.Delete(file);
                     }
                 }
             }
         }
The documentation for this class was generated from the following file:
Program.cs