Open Source XML & JSON Visualisation Software: OSXJV.Server.OSXJVServer Class Reference
OSXJV.Server.OSXJVServer Class Reference
HTTPServer that process the incoming requests.
Public Member Functions
OSXJVServer ()
The Server Handler
bool Start ()
Starts server in new thread
bool Stop ()
Stop the listener and about all current requests
void Run ()
Function that constantly listens for connections
Request GetFormData (Stream input)
Extract the files from the request
Static Public Attributes
static bool running = false
True if the server is able to accept requests.
Private Member Functions
void ListenerCallback (IAsyncResult result)
Handles Requests Asyncronously
void HandleClient (HttpListenerContext c)
Handles the client
void HandleOptions (HttpListenerResponse response)
Sends to the Client What the Server Supports
Request GetFileData (Stream input, string type)
Get Data if the data is retrieved
Response HandlePost (HttpListenerRequest req)
Handles a POST request.
Response HandleGet (HttpListenerRequest req)
Handles a GET request.
void SaveFile (string id, Node nodes)
Save data recievied from client.
void Post (Response res, HttpListenerResponse stream)
Send data to the client.
Request GetData (HttpListenerRequest req)
Get the data from the client.
string SegmentNormalize (string input)
Removes '/' from the string.
Private Attributes
int port = 8082
HttpListener listener
Thread serverThread = null
Detailed Description
HTTPServer that process the incoming requests.
Definition at line 16 of file OSXJVServer.cs.
Constructor & Destructor Documentation
OSXJVServer()
OSXJV.Server.OSXJVServer.OSXJVServer ()
The Server Handler
Definition at line 34 of file OSXJVServer.cs.
         {
             listener = new HttpListener();
             listener.Prefixes.Add("http://localhost:" + port + "/"); //change if need be
         }
Member Function Documentation
GetData()
Request OSXJV.Server.OSXJVServer.GetData (HttpListenerRequest req) private
Get the data from the client.
Parameters
req The request from the client
Returns
A Request Object
Definition at line 413 of file OSXJVServer.cs.
         {
             Request r = null;
             if (req.ContentType.Contains("application/x-www-form-urlencoded"))
             {
                 r = GetFormData(req.InputStream);
             }
             else if (req.ContentType.Contains("application/json") || req.ContentType.Contains("application/oclet-stream"))
             {
                 r = GetFileData(req.InputStream, "application/json");
             }
             else if (req.ContentType.Contains("application/xml") || req.ContentType.Contains("text/xml"))
             {
                 r = GetFileData(req.InputStream, "text/xml");
             }
             return r;
         }
GetFileData()
Request OSXJV.Server.OSXJVServer.GetFileData (Stream input, string type) private
Get Data if the data is retrieved
Parameters
input Client Stream Input
type The MIME type
Returns
A Response object to send to the user
Definition at line 209 of file OSXJVServer.cs.
References OSXJV.Classes.Request.GetRequest().
         {
             string request = "";
             using (StreamReader ms = new StreamReader(input))
             {
                 request = ms.ReadToEnd();
             }
             string filename = "temp";
             if (type == "text/xml")
                 filename += ".xml";
             else if(type == "application/json")
                 filename += ".json";
             else
                 filename += ".html";
             return Request.GetRequest(filename,type, request);
         }
GetFormData()
Request OSXJV.Server.OSXJVServer.GetFormData (Stream input)
Extract the files from the request
Parameters
input Requests input stream
Returns
New Request Object
Exceptions
System.InvalidOperationException Thrown when no files are included with the request
Definition at line 185 of file OSXJVServer.cs.
References OSXJV.Classes.Request.GetRequest().
         {
             string request = "";
             MultipartFormDataParser parser = new MultipartFormDataParser(input);
             if (parser.Files.Count > 0)
             {
                 using (StreamReader ms = new StreamReader(parser.Files[0].Data))
                 {
                     request = ms.ReadToEnd();
                 }
             }
             else
             {
                 throw new InvalidOperationException();
             }
             return Request.GetRequest(parser.Files[0].FileName, parser.Files[0].ContentType, request);
         }
HandleClient()
void OSXJV.Server.OSXJVServer.HandleClient (HttpListenerContext c) private
Handles the client
Parameters
c The Request
Definition at line 146 of file OSXJVServer.cs.
References OSXJV.Classes.Response.GetInvalidRequestResponse(), and OSXJV.Classes.Response.Response().
         {
             switch(c.Request.HttpMethod)
             {
                 case "POST":
                     Post(HandlePost(c.Request),c.Response);
                     break;
                 case "GET":
                     Post(HandleGet(c.Request), c.Response);
                     break;
                 case "OPTIONS":
                     HandleOptions(c.Response);
                     c.Response.Close();
                     break;
                 default:
                     Post(Response.GetInvalidRequestResponse(), c.Response);
                     break;
             }
         }
HandleGet()
Response OSXJV.Server.OSXJVServer.HandleGet (HttpListenerRequest req) private
Handles a GET request.
Parameters
req The request to be processed.
Returns
A Response object to send to the user
Definition at line 312 of file OSXJVServer.cs.
References OSXJV.Classes.Output.CreateView(), OSXJV.Classes.Response.GetErrorResponse(), OSXJV.Classes.CacheManager.getFile(), OSXJV.Classes.CacheManager.GetInstance(), OSXJV.Classes.Logger.GetInstance(), OSXJV.Classes.Response.GetInvalidRequestResponse(), OSXJV.Classes.Response.GetResponse(), and OSXJV.Classes.Logger.WriteError().
         {
             if (SegmentNormalize(req.Url.Segments[1]).Equals("Process"))
             {
                 if (req.Url.Segments.Length == 4)
                 {
                     Node cached;
                     try
                     {
                         cached = JsonConvert.DeserializeObject<Node>(CacheManager.GetInstance().getFile(req.Url.Segments[2]));
                     }
                     catch (Exception e)
                     {
                         Logger.GetInstance().WriteError(e.Message);
                         JObject eRes = new JObject();
                         eRes.Add("Error", "Error Creating Response");
                         return Response.GetErrorResponse(eRes.ToString());
                     }
                     Output o = new Output(cached);
                     JObject response = new JObject();
                     response.Add("view", o.CreateView(int.Parse(req.Url.Segments[3])));
                     byte[] bytes = Encoding.UTF8.GetBytes(response.ToString());
                     return Response.GetResponse(200, "application/json", bytes);
                 }
                 else if (req.Url.Segments.Length == 5)
                 {
                     Node cached;
                     try
                     {
                         cached = JsonConvert.DeserializeObject<Node>(CacheManager.GetInstance().getFile(req.Url.Segments[2]));
                     }
                     catch (Exception e)
                     {
                         Logger.GetInstance().WriteError(e.Message);
                         JObject eRes = new JObject();
                         eRes.Add("Error", "Error Creating Response");
                         return Response.GetErrorResponse(eRes.ToString());
                     }
                     Output o = new Output(cached);
                     JObject response = new JObject();
                     response.Add("view", o.CreateView(int.Parse(SegmentNormalize(req.Url.Segments[3])), 4, int.Parse(SegmentNormalize(req.Url.Segments[4]))));
                     byte[] bytes = Encoding.UTF8.GetBytes(response.ToString());
                     return Response.GetResponse(200, "application/json", bytes);
                 }
                 else
                     return Response.GetInvalidRequestResponse();
             }
             //If it got here its an invalid response.
             return Response.GetInvalidRequestResponse();
         }
HandleOptions()
void OSXJV.Server.OSXJVServer.HandleOptions (HttpListenerResponse response) private
Sends to the Client What the Server Supports
Parameters
response The Request Response Object
Definition at line 170 of file OSXJVServer.cs.
         {
             response.AddHeader("Access-Control-Allow-Headers", "Content-Type, Accept, X-Requested-With");
             response.AddHeader("Access-Control-Allow-Methods", "POST");
             response.AddHeader("Access-Control-Allow-Methods", "GET");
             response.AddHeader("Access-Control-Max-Age", "1728000");
             response.AppendHeader("Access-Control-Allow-Origin", "*");
         }
HandlePost()
Response OSXJV.Server.OSXJVServer.HandlePost (HttpListenerRequest req) private
Handles a POST request.
Parameters
req The request to be processed.
Returns
A Response object to send to the user
Definition at line 233 of file OSXJVServer.cs.
References OSXJV.Classes.Validation.CheckDocument(), OSXJV.Classes.Output.CreateGrid(), OSXJV.Classes.Output.CreateView(), OSXJV.Classes.Request.Data, OSXJV.Classes.Response.GetErrorResponse(), OSXJV.Classes.CacheManager.GetInstance(), OSXJV.Classes.Logger.GetInstance(), OSXJV.Classes.Response.GetInvalidRequestResponse(), OSXJV.Classes.ProcessDocument.GetProcess(), OSXJV.Classes.Response.GetResponse(), OSXJV.Classes.ProcessDocument.ProcessParallel(), OSXJV.Classes.CacheManager.saveFile(), OSXJV.Classes.Request.Type, and OSXJV.Classes.Logger.WriteError().
         {
             JObject eRes = new JObject();
             if (SegmentNormalize(req.RawUrl).Equals("Process"))
             {
                 if (req.HasEntityBody)
                 {
                     Request r = null;
                     try
                     {
                         r = GetData(req);
                         if (r == null)
                             return Response.GetInvalidRequestResponse();
                     }
                     catch
                     {
                        return Response.GetInvalidRequestResponse();
                     }
                     try
                     {
                         Validation.CheckDocument(r.Data, r.Type);
                     }
                     catch (Exception e)
                     {
                         eRes.Add("Error", e.Message);
                         return Response.GetErrorResponse(eRes.ToString());
                     }
                     string id = Guid.NewGuid().ToString();
                     ProcessDocument pro = ProcessDocument.GetProcess(r.Data, r.Type);
                     Node n = pro.ProcessParallel();
                     Output o = new Output(n); //new output object
                     try
                     {
                         CacheManager.GetInstance().saveFile(id, JsonConvert.SerializeObject(n));
                         JObject response = new JObject();
                         n = null; //remove node as its completed;
                         response.Add("filename", id);
                         response.Add("grid", o.CreateGrid());
                         response.Add("view", o.CreateView());
                         byte[] bytes = Encoding.UTF8.GetBytes(response.ToString());
                         return Response.GetResponse(200, "application/json", bytes);
                     }
                     catch (Exception e)
                     {
                         Logger.GetInstance().WriteError(e.Message);
                         eRes.Add("Error", "Error Creating Response");
                         return Response.GetErrorResponse(eRes.ToString());
                     }
                 }
                 eRes.Add("Error", "No File Recieved By Server");
                 return Response.GetErrorResponse(eRes.ToString());
             }
             else if (req.RawUrl.Equals("/Output"))
             {
                 return Response.GetInvalidRequestResponse();
             }
             else
                 return Response.GetInvalidRequestResponse();
         }
ListenerCallback()
void OSXJV.Server.OSXJVServer.ListenerCallback (IAsyncResult result) private
Handles Requests Asyncronously
Parameters
result The Request Object Coming In.
Definition at line 124 of file OSXJVServer.cs.
References OSXJV.Classes.Logger.GetInstance(), and OSXJV.Classes.Logger.WriteError().
         {
             HttpListener listener = (HttpListener)result.AsyncState;
             HttpListenerContext context = listener.EndGetContext(result);
             try
             {
                 HandleClient(context);
             }
             catch (Exception e)
             {
                 Logger.GetInstance().WriteError(e.Message);
                 context.Response.StatusCode = 500;
                 context.Response.Close();
             }
         }
Post()
void OSXJV.Server.OSXJVServer.Post (Response res, HttpListenerResponse stream) private
Send data to the client.
Parameters
res The Response Object
stream The Client Output Stream
///
Exceptions
ArgumentException Thrown when Response is null or HttpListenerResponse is null or empty
Definition at line 394 of file OSXJVServer.cs.
References OSXJV.Classes.Response.data, OSXJV.Classes.Response.mime, and OSXJV.Classes.Response.status.
         {
             if (res == null || stream == null)
                 throw new ArgumentException("Response or Client Stream cannot be NULL");
             HandleOptions(stream);
             stream.ProtocolVersion = new Version(1, 1);
             stream.StatusCode = res.status;
             stream.ContentType = res.mime;
             stream.ContentLength64 = res.data.Length;
             stream.OutputStream.Write(res.data, 0, res.data.Length);
             stream.Close();
         }
Run()
void OSXJV.Server.OSXJVServer.Run ()
Function that constantly listens for connections
Definition at line 76 of file OSXJVServer.cs.
         {
             running = true;
             listener.Start();
             while(listener.IsListening)
             {
                 Console.WriteLine("Waiting");
                 //Wait for Listener
                 IAsyncResult result = listener.BeginGetContext(new AsyncCallback(ListenerCallback), listener);
                 result.AsyncWaitHandle.WaitOne();
                 if (result.CompletedSynchronously)
                     Console.WriteLine("Completed Synchronously");
                 /*
                  * Old Method of Creating a Thread
                  *
                 Thread response = new Thread(() =>
                 {
                     try
                     {
                         Console.WriteLine("Processing");
                         HandleClient(hlc);
                         Console.WriteLine("Finished");
                     }
                     catch(Exception e)
                     {
                         Logger.GetInstance().WriteError(e.Message);
                         hlc.Response.StatusCode = 500;
                         hlc.Response.Close();
                     }
                 });
                 response.Start();
                 *
                 */
             }
         }
SaveFile()
void OSXJV.Server.OSXJVServer.SaveFile (string id, Node nodes) private
Save data recievied from client.
Parameters
id Unique ID
nodes The Processed Data
Exceptions
ArgumentException Thrown when nodes is null or id is null or empty
Definition at line 371 of file OSXJVServer.cs.
References OSXJV.Classes.CacheManager.GetInstance(), OSXJV.Classes.Logger.GetInstance(), OSXJV.Classes.CacheManager.saveFile(), and OSXJV.Classes.Logger.WriteError().
         {
             if(nodes == null || string.IsNullOrEmpty(id))
             {
                 throw new ArgumentException();
             }
             try
             {
                 CacheManager.GetInstance().saveFile(id, JsonConvert.SerializeObject(nodes));
             }
             catch (Exception e)
             {
                 Logger.GetInstance().WriteError(e.Message);
             }
         }
SegmentNormalize()
string OSXJV.Server.OSXJVServer.SegmentNormalize (string input) private
Removes '/' from the string.
Parameters
input A string from the URL
Returns
Normalised String
Definition at line 437 of file OSXJVServer.cs.
         {
             return input.Replace("/", "");
         }
Start()
bool OSXJV.Server.OSXJVServer.Start ()
Starts server in new thread
Definition at line 43 of file OSXJVServer.cs.
Referenced by WebServer.Program.Main().
         {
             serverThread = new Thread(new ThreadStart(Run));
             try
             {
                 serverThread.Start();
             }
             catch
             {}
             return serverThread.IsAlive;
         }
Stop()
bool OSXJV.Server.OSXJVServer.Stop ()
Stop the listener and about all current requests
Definition at line 58 of file OSXJVServer.cs.
         {
             if (listener != null)
                 if (listener.IsListening)
                     listener.Abort();
             if (serverThread != null)
             {
                 serverThread.Join();
                 serverThread = null;
             }
             return serverThread == null ?true:false;
         }
Member Data Documentation
listener
HttpListener OSXJV.Server.OSXJVServer.listener private
Definition at line 24 of file OSXJVServer.cs.
port
int OSXJV.Server.OSXJVServer.port = 8082 private
Definition at line 18 of file OSXJVServer.cs.
running
bool OSXJV.Server.OSXJVServer.running = false static
True if the server is able to accept requests.
Definition at line 23 of file OSXJVServer.cs.
serverThread
Thread OSXJV.Server.OSXJVServer.serverThread = null private
Definition at line 29 of file OSXJVServer.cs.
The documentation for this class was generated from the following file:
OSXJVServer.cs