Open Source XML & JSON Visualisation Software: OSXJV.Classes.Logger Class Reference
OSXJV.Classes.Logger Class Reference
A simple class that writes errors to a single file.
Public Member Functions
void WriteError (string error)
Writes an error the location provided
Static Public Member Functions
static bool Setup (string location)
static Logger GetInstance ()
Gets the single instance of Logger
static void Close ()
Private Member Functions
Logger (string location)
Private Attributes
string location
Static Private Attributes
static Logger inst
Singleton instance of Logger
Detailed Description
A simple class that writes errors to a single file.
Definition at line 9 of file Logger.cs.
Constructor & Destructor Documentation
Logger()
OSXJV.Classes.Logger.Logger (string location) private
Definition at line 17 of file Logger.cs.
         {
             this.location = location;
         }
Member Function Documentation
Close()
static void OSXJV.Classes.Logger.Close () static
Definition at line 72 of file Logger.cs.
         {
             if (inst == null)
                 throw new Exception("Logger Already Closed");
             else
                 inst = null;
         }
GetInstance()
static Logger OSXJV.Classes.Logger.GetInstance () static
Gets the single instance of Logger
Returns
Instance of Logger
Definition at line 41 of file Logger.cs.
Referenced by OSXJV.Server.OSXJVServer.HandleGet(), OSXJV.Server.OSXJVServer.HandlePost(), OSXJV.Server.OSXJVServer.ListenerCallback(), and OSXJV.Server.OSXJVServer.SaveFile().
         {
             if (inst != null)
                 return inst;
             else
                 throw new Exception("Logger has not been setup");
         }
Setup()
static bool OSXJV.Classes.Logger.Setup (string location) static
Parameters
location
Definition at line 26 of file Logger.cs.
Referenced by WebServer.Program.Main().
         {
             if (string.IsNullOrEmpty(location))
                 throw new ArgumentException("Location cannot be empty");
             if (!Directory.Exists(string.Format(@"{0}", location)))
                 throw new Exception("Location is not a valid logger directory");
             return (inst = new Logger(location)) != null ? true:false;
         }
WriteError()
void OSXJV.Classes.Logger.WriteError (string error)
Writes an error the location provided
Parameters
error The error message
Definition at line 53 of file Logger.cs.
Referenced by OSXJV.Server.OSXJVServer.HandleGet(), OSXJV.Server.OSXJVServer.HandlePost(), OSXJV.Server.OSXJVServer.ListenerCallback(), and OSXJV.Server.OSXJVServer.SaveFile().
         {
             try
             {
                 if (!string.IsNullOrEmpty(error))
                 {
                     string file = string.Format(@"{0}/Error-{1}.txt", location, DateTime.Now.ToString("dd-MM-yy hh-MM-ss"));
                     StreamWriter sw = new StreamWriter(file);
                     sw.WriteLine(error);
                     sw.WriteLine();
                     sw.Close();
                 }
             }
             catch (IOException e)
             {
                 throw e;
             }
         }
Member Data Documentation
inst
Logger OSXJV.Classes.Logger.inst static private
Singleton instance of Logger
Definition at line 14 of file Logger.cs.
location
string OSXJV.Classes.Logger.location private
Definition at line 15 of file Logger.cs.
The documentation for this class was generated from the following file:
OSXJVClasses/Logger.cs