Open Source XML & JSON Visualisation Software: OSXJV.Classes.Response Class Reference
OSXJV.Classes.Response Class Reference
The Object containing data to send to the client
Static Public Member Functions
static Response GetResponse (int status, string type, byte[] data)
A custom response object
static Response GetResponseJSON (int status, byte[] data)
Return an application/json response
static Response GetResponseXML (int status, byte[] data)
Return an text/xml response
static Response GetErrorResponse (string message)
Return a error response object
static Response GetInvalidRequestResponse ()
Returns an invalid response object
Public Attributes
byte [] data = null
Data
int status
Status Code
string mime
Data type e.g. "application/json"
Private Member Functions
Response (int status, string mime, byte[] buffer)
Constructor
Detailed Description
The Object containing data to send to the client
Definition at line 9 of file Response.cs.
Constructor & Destructor Documentation
Response()
OSXJV.Classes.Response.Response (int status, string mime, byte [] buffer) private
Constructor
Parameters
status Status Code
mime MIME type
buffer Data
Definition at line 34 of file Response.cs.
Referenced by OSXJV.Server.OSXJVServer.HandleClient().
         {
             this.status = status;
             this.data = buffer;
             this.mime = mime;
         }
Member Function Documentation
GetErrorResponse()
static Response OSXJV.Classes.Response.GetErrorResponse (string message) static
Return a error response object
Returns
New response object
Definition at line 118 of file Response.cs.
Referenced by OSXJV.Server.OSXJVServer.HandleGet(), and OSXJV.Server.OSXJVServer.HandlePost().
         {
             byte[] res = Encoding.UTF8.GetBytes(message);
             return new Response(400, "text/html", res);
         }
GetInvalidRequestResponse()
static Response OSXJV.Classes.Response.GetInvalidRequestResponse () static
Returns an invalid response object
Returns
New response object
Definition at line 128 of file Response.cs.
Referenced by OSXJV.Server.OSXJVServer.HandleClient(), OSXJV.Server.OSXJVServer.HandleGet(), and OSXJV.Server.OSXJVServer.HandlePost().
         {
             return new Response(405, "text/html", new byte[0]);
         }
GetResponse()
static Response OSXJV.Classes.Response.GetResponse (int status, string type, byte [] data) static
A custom response object
Parameters
status The HTTP Code to send back e.g. 200 for success
type Data type to send back e.g. application/json
data The data to send
Returns
Definition at line 48 of file Response.cs.
Referenced by OSXJV.Server.OSXJVServer.HandleGet(), and OSXJV.Server.OSXJVServer.HandlePost().
         {
             if(string.IsNullOrEmpty(type))
                 throw new ArgumentException("Type cannot be Null or empty");
             if (status.Equals(null))
                 throw new ArgumentException("Status cannot be Null");
             else
                if (status == 0)
                 throw new ArgumentException("Status cannot be 0");
             if (data == null)
                 throw new ArgumentException("Data cannot be null");
             else
                 if (data.Length == 0)
                 throw new ArgumentException("No data, use invalid or error response");
             return new Response(status, type, data);
         }
GetResponseJSON()
static Response OSXJV.Classes.Response.GetResponseJSON (int status, byte [] data) static
Return an application/json response
Parameters
status The HTTP Code to send back e.g. 200 for success
data The data to send
Returns
New response object
Definition at line 74 of file Response.cs.
         {
             if (status.Equals(null))
                 throw new ArgumentException("Status cannot be Null");
             else
                 if (status == 0)
                     throw new ArgumentException("Status cannot be 0");
             if (data == null)
                 throw new ArgumentException("Data cannot be null");
             else
                 if (data.Length == 0)
                     throw new ArgumentException("No data, use invalid or error response");
             return new Response(status,"application/json", data);
         }
GetResponseXML()
static Response OSXJV.Classes.Response.GetResponseXML (int status, byte [] data) static
Return an text/xml response
Parameters
status The HTTP Code to send back e.g. 200 for success
data The data to send
Returns
New response object
Definition at line 97 of file Response.cs.
         {
             if (status.Equals(null))
                 throw new ArgumentException("Status cannot be Null");
             else
                 if(status == 0)
                     throw new ArgumentException("Status cannot be 0");
             if (data == null)
                 throw new ArgumentException("Data cannot be null");
             else
                 if (data.Length == 0)
                     throw new ArgumentException("No data, use invalid or error response");
             return new Response(status, "text/xml", data);
         }
Member Data Documentation
data
byte [] OSXJV.Classes.Response.data = null
Data
Definition at line 14 of file Response.cs.
Referenced by OSXJV.Server.OSXJVServer.Post().
mime
string OSXJV.Classes.Response.mime
Data type e.g. "application/json"
Definition at line 24 of file Response.cs.
Referenced by OSXJV.Server.OSXJVServer.Post().
status
int OSXJV.Classes.Response.status
Status Code
Definition at line 19 of file Response.cs.
Referenced by OSXJV.Server.OSXJVServer.Post().
The documentation for this class was generated from the following file:
OSXJVClasses/Response.cs