Open Source XML & JSON Visualisation Software: OSXJV.Classes.Output Class Reference
OSXJV.Classes.Output Class Reference
Creates the Output for the web page to display.
Public Member Functions
Output (Node nodes)
Creation of a Output object.
JObject CreateGrid ()
Creates the grid data.
string CreateViewSingle (int node, int nodeStart=0)
CreateView using a Single Thread
string CreateView (int node=1, int pCount=4, int nodeStart=0)
Creates the view of nodes using multiple threads.
Private Member Functions
JObject GridGetChidren (Node n)
Recursive function to get all the nodes data for the grid .
string CreateExtraNode (string type, int id)
Builds a get more button to display
string CreatePreviousNode (string type, int leftVal, int topVal, int id)
Create a previous node button
string CreateExtraNode (string type, int leftVal, int topVal, int id)
Create a extra node button
void CreateNodeChildViewsParallel (List< Node > job, int start, bool showHigher, int next, int previous)
Generate Output HTML when using multi-threads
string CheckChildren (Node n, int number)
Check child nodes if the are to be part of the output.
string CheckChildren (Node n, int number, int pCount, int nodeStart, ref bool found)
void GetParent (Node node, int number)
Finds the parent node.
string CreateNodeView (Node n, string type, int leftVal, int topVal)
Generates HTML for the Specific Node (Multi-Threaded Version)
string CreateNodeView (Node n, string type)
Generates HTML for specific Node (Single Threaded Version)
bool CheckNodeNumber (Node n, int number)
Checks if Node number and inputted number match.
Private Attributes
int left = 100
int top = 130
Node nodes
bool GotParent = false
int Parent = 0
Parent of node when building output (Used when getting Node other than root).
List< Tuple< int, string > > cNodes = new List<Tuple<int, string>>()
Used in Threading, list of calculated HTML strings.
Static Private Attributes
static int count = 0
Used in Single Threaded operation to keep track of div id.
Detailed Description
Creates the Output for the web page to display.
Definition at line 11 of file Output.cs.
Constructor & Destructor Documentation
Output()
OSXJV.Classes.Output.Output (Node nodes)
Creation of a Output object.
Parameters
nodes A processed object of Nodes
Definition at line 48 of file Output.cs.
         {
             if (nodes == null)
                 throw new ArgumentException();
             this.nodes = nodes;
         }
Member Function Documentation
CheckChildren() [1/2]
string OSXJV.Classes.Output.CheckChildren (Node n, int number) private
Check child nodes if the are to be part of the output.
Parameters
n Node to search
number Number to check
Returns
String of calculated HTML
Definition at line 405 of file Output.cs.
References OSXJV.Classes.Node.Children, and OSXJV.Classes.Node.Number.
         {
             string output = "";
             if (CheckNodeNumber(n, number))
             {
                 List<Thread> threadList = new List<Thread>();
                 int count = 0;
                 output += CreateNodeView(n, "node");
                 foreach (Node n2 in n.Children)
                 {
                     count++;
                     output += CreateNodeView(n2, "node-child");
                 }
             }
             else if (n.Children.Count > 0)
             {
                 foreach (Node n2 in n.Children)
                 {
                     if (GotParent)
                     {
                         if (n2.Number == Parent)
{
                             output += CreateNodeView(n2, "node-parent");
                         }
                     }
                     output += CheckChildren(n2, number);
                 }
             }
             return output;
         }
CheckChildren() [2/2]
string OSXJV.Classes.Output.CheckChildren (Node n, int number, int pCount, int nodeStart, ref bool found) private
Parameters
n
number
pCount
nodeStart
found
Returns
String of calculated HTML
Definition at line 449 of file Output.cs.
References OSXJV.Classes.Node.Children, and OSXJV.Classes.Node.Number.
         {
             string output = "";
             if (CheckNodeNumber(n, number))
             {
                 found = true;
                 List<Thread> threadList = new List<Thread>();
                 int count = 0;
                 output += CreateNodeView(n, "node");
                 count++;
                 //output += CreateNodeView(n2, "node-child");
                 int childCount = 0;
                 if (n.Children.Count < 200)
                     childCount = n.Children.Count;
                 else
                 {
                     childCount = 200;
                 }
                 if (childCount < pCount * 2)
                 {
                     foreach(Node n2 in n.Children)
                     {
                         output += CreateNodeView(n2, "node-child");
                     }
                 }
                 else
                 {
                     int spread = (int)Math.Ceiling((double)childCount / (double)pCount);
                     if (childCount > 0)
                     {
                         for (int i = 0; i < pCount; i++)
{
                             int neg = 0;
                             if ((spread * (i + 1)) > childCount)
{
                                 neg = childCount - (spread * (i + 1));
                             }
                             int start = (spread * i);
                             int rangeStart = (spread * i) + nodeStart;
                             bool showHigher = nodeStart != 0 ? true : false;
                             List<Node> NodesToProcess = n.Children.GetRange(rangeStart, spread + neg);
                             if (NodesToProcess.Count > 0)
{
                                 Thread threadJob = new Thread(() => CreateNodeChildViewsParallel(NodesToProcess, start, showHigher, childCount + nodeStart, nodeStart - childCount));
                                 threadJob.Name = i.ToString();
                                 threadJob.Start();
                                 threadList.Add(threadJob);
                             }
                         }
                         foreach (Thread t in threadList)
{
                             t.Join();
                         }
                         cNodes.Sort((x, y) => x.Item1.CompareTo(y.Item1));
                         foreach (Tuple<int, string> tup in cNodes)
{
                             output += tup.Item2;
                         }
                     }
                 }
             }
             else if (n.Children.Count > 0)
             {
                 foreach (Node n2 in n.Children)
                 {
                     if (GotParent)
                     {
                         if (n2.Number == Parent)
{
                             output += CreateNodeView(n2, "node-parent");
                         }
                     }
                     output += CheckChildren(n2, number,pCount,nodeStart,ref found);
                 }
             }
             return output;
         }
CheckNodeNumber()
bool OSXJV.Classes.Output.CheckNodeNumber (Node n, int number) private
Checks if Node number and inputted number match.
Parameters
n Node to search
number Number to match with
Returns
Definition at line 670 of file Output.cs.
References OSXJV.Classes.Node.Number.
         {
             return n.Number.Equals(number);
         }
CreateExtraNode() [1/2]
string OSXJV.Classes.Output.CreateExtraNode (string type, int id) private
Builds a get more button to display
Parameters
type Node type e.g. 'node-child'
id The id of the node to start from
Returns
String of calculated HTML
Definition at line 170 of file Output.cs.
         {
             string node = "";
             if (type == "node")
             {
                 if (GotParent)
                 {
                     left = left + 400;
                 }
             }
             if (type == "node-child")
             {
                 left = left + 400;
             }
             node += "<div class='node-child type ui-draggable ui-selectee' style='left:" + left + "px; top:" + top + "px;margin-bottom:50px;'>";
             node += "<div class='head'><span><button class='nameBtn' onclick='GetMoreNodes(" + id + ")'>Show Lower</button></span></div>";
             node += "</div></div>";
             return node;
         }
CreateExtraNode() [2/2]
string OSXJV.Classes.Output.CreateExtraNode (string type, int leftVal, int topVal, int id) private
Create a extra node button
Parameters
type Node type e.g. 'node-child'
leftVal Margin from the left of the display
topVal Margin from the top of the display
id The id of the node to start from
Returns
String of calculated HTML
Definition at line 229 of file Output.cs.
         {
             string node = "";
             if (type == "node")
             {
                 if (GotParent)
                 {
                     leftVal = leftVal + 400;
                 }
             }
             if (type == "node-child")
             {
                 leftVal = leftVal + 400;
             }
             node += "<div class='node-child type ui-draggable ui-selectee' style='left:" + leftVal + "px; top:" + topVal + "px;margin-bottom:50px;'>";
             node += "<div class='head'><span><button class='nameBtn' onclick='GetMoreNodes(" + id + ")'>Show Lower</button></span></div>";
             node += "</div></div>";
             return node;
         }
CreateGrid()
JObject OSXJV.Classes.Output.CreateGrid ()
Creates the grid data.
Returns
A JSON object
Definition at line 59 of file Output.cs.
References OSXJV.Classes.Node.Children, OSXJV.Classes.Node.Name, and OSXJV.Classes.Node.Number.
Referenced by OSXJV.Server.OSXJVServer.HandlePost().
         {
             JObject obj = new JObject();
             obj.Add("text", nodes.Name);
             obj.Add("id", nodes.Number);
             obj.Add("state", new JObject(new JProperty("selected", true)));
             if(nodes.Children.Count > 0)
             {
                 JArray array = new JArray();
                 foreach (Node n2 in nodes.Children)
                 {
                     array.Add(GridGetChidren(n2));
                 }
                 obj.Add("children", array);
             }
             return obj;
         }
CreateNodeChildViewsParallel()
void OSXJV.Classes.Output.CreateNodeChildViewsParallel (List< Node > job, int start, bool showHigher, int next, int previous) private
Generate Output HTML when using multi-threads
Parameters
job The Nodes to process
start Start index
showHigher if the are nodes higher up, show previous button
next Next value for next button
previous Previous value for previous button
Definition at line 258 of file Output.cs.
References OSXJV.Classes.Node.Comments.
         {
             int threadID = int.Parse(Thread.CurrentThread.Name);
             string type = "node-child";
             string output = "";
             if(start == 0 && showHigher)
             {
                 output += CreatePreviousNode(type, left, top, previous);
             }
             bool hadCommentsPrev = false;
             int numCommentsPrevious = 0;
             foreach(Node n in job)
             {
                 int extra = showHigher ? 130 * (start +1) : 130 * start;
                 if (hadCommentsPrev)
                     extra += (numCommentsPrevious * 25);
                 if (n.Comments.Count > 0)
                 {
                     hadCommentsPrev = true;
                     numCommentsPrevious = n.Comments.Count;
                 }
                 else
                     hadCommentsPrev = false;
                 output += CreateNodeView(n, type,left,top + extra);
                 start++;
                 if (start == 200)
                 {
                     output += CreateExtraNode(type, left, top + extra + 130,next);
                     break;
                 }
             }
             cNodes.Add(new Tuple<int, string>(threadID, output));
         }
CreateNodeView() [1/2]
string OSXJV.Classes.Output.CreateNodeView (Node n, string type, int leftVal, int topVal) private
Generates HTML for the Specific Node (Multi-Threaded Version)
Parameters
n Node to parse
type Type of node
leftVal Margin left of display
topVal Margin top of display
Returns
String of calculated HTML
Definition at line 566 of file Output.cs.
References OSXJV.Classes.Node.Attributes, OSXJV.Classes.Node.Comments, OSXJV.Classes.Attribute.Name, OSXJV.Classes.Node.Name, OSXJV.Classes.Node.Number, OSXJV.Classes.Attribute.Value, and OSXJV.Classes.Node.Value.
         {
             string node = "";
             if(type == "node")
             {
                 if(GotParent)
                 {
                     leftVal = leftVal + 400;
                 }
             }
             if(type == "node-child")
             {
                 leftVal = leftVal + 400;
             }
             node += "<div id='" + n.Number + "'class='" + type + " type ui-draggable ui-selectee' style='left:" + leftVal + "px; top:" + topVal + "px;'>";
             node += "<div class='head'><span><button class='nameBtn' onclick='GetNode("+n.Number+")'>" + n.Name + "</button></span></div>";
             if (!string.IsNullOrEmpty(n.Value))
             {
                 node += string.Format("<div class='blockR'><p>Value</p></div><div class=comment><span>{0}</span></div>", n.Value);
             }
             if(n.Comments.Count >0)
             {
                 node += "<div><p class='text-center'>Comments</p></div>";
                 foreach(string com in n.Comments)
                 {
                     node += "<div class='comment'>" + com + "</div>";
                 }
             }
             if (n.Attributes.Count > 0)
             {
                 node += "<div class='attribute'><div class='aHeader'><p><button><i class='fa fa-plus'></i></button>Attributes</p></div><div class='options'>";
                 foreach (Attribute a in n.Attributes)
                 {
                     node += string.Format("<div class='blockR'><p>{0}</p></div><div class='comment'><p>{1}</p></div>", a.Name, a.Value);
                 }
                 node += "</div>";
             }
             node += "</div></div>";
             return node;
         }
CreateNodeView() [2/2]
string OSXJV.Classes.Output.CreateNodeView (Node n, string type) private
Generates HTML for specific Node (Single Threaded Version)
Parameters
n Node to parse
type Type of node
Returns
String of calculated HTML
Definition at line 615 of file Output.cs.
References OSXJV.Classes.Node.Attributes, OSXJV.Classes.Node.Comments, OSXJV.Classes.Attribute.Name, OSXJV.Classes.Node.Name, OSXJV.Classes.Node.Number, OSXJV.Classes.Attribute.Value, and OSXJV.Classes.Node.Value.
         {
             string node = "";
             int leftVal = left;
             if (type == "node")
             {
                 if (GotParent)
                 {
                     left = left + 400;
                     leftVal = left;
                 }
             }
             if (type == "node-child")
             {
                 leftVal = leftVal + 400;
             }
             node += "<div id='" + n.Number + "'class='" + type + " type ui-draggable ui-selectee' style='left:" + leftVal + "px; top:" + top + "px;'>";
             node += "<div class='head'><span><button class='nameBtn' onclick='GetNode(" + n.Number + ")'>" + n.Name + "</button></span></div>";
             if (!string.IsNullOrEmpty(n.Value))
             {
                 node += string.Format("<div class='blockR'><p>Value</p></div><div class=comment><span>{0}</span></div>", n.Value);
             }
             if (n.Comments.Count > 0)
             {
                 node += "<div><p class='text-center'>Comments</p></div>";
                 foreach (string com in n.Comments)
                 {
                     node += "<div class='comment'>" + com + "</div>";
                 }
             }
             if (n.Attributes.Count > 0)
             {
                 node += "<div class='attribute'><div class='aHeader'><p><button><i class='fa fa-plus'></i></button>Attributes</p></div><div class='options'>";
                 foreach (Attribute a in n.Attributes)
                 {
                     node += string.Format("<div class='blockR'><p>{0}</p></div><div class='comment'><p>{1}</p></div>", a.Name, a.Value);
                 }
                 node += "</div>";
             }
             node += "</div></div>";
             if (type == "node-child")
             {
                 top = top + 130;
             }
             return node;
         }
CreatePreviousNode()
string OSXJV.Classes.Output.CreatePreviousNode (string type, int leftVal, int topVal, int id) private
Create a previous node button
Parameters
type Node type e.g. 'node-child'
leftVal Margin from the left of the display
topVal Margin from the top of the display
id The id of the node to start from
Returns
String of calculated HTML
Definition at line 200 of file Output.cs.
         {
             string node = "";
             if (type == "node")
             {
                 if (GotParent)
                 {
                     leftVal = leftVal + 400;
                 }
             }
             if (type == "node-child")
             {
                 leftVal = leftVal + 400;
             }
             node += "<div class='node-child type ui-draggable ui-selectee' style='left:" + leftVal + "px; top:" + topVal + "px;'>";
             node += "<div class='head'><span><button class='nameBtn' onclick='GetMoreNodes(" + id + ")'>Show Higher</button></span></div>";
             node += "</div></div>";
             return node;
         }
CreateView()
string OSXJV.Classes.Output.CreateView (int node = 1, int pCount = 4, int nodeStart = 0)
Creates the view of nodes using multiple threads.
Parameters
node Number of node to start from. Default is 1(Root)
pCount Number of Threads to use. Default is 4
nodeStart Where to start the child nodes from
Returns
String of calculated HTML
Definition at line 306 of file Output.cs.
References OSXJV.Classes.Node.Children, and OSXJV.Classes.Node.Number.
Referenced by OSXJV.Server.OSXJVServer.HandleGet(), and OSXJV.Server.OSXJVServer.HandlePost().
         {
             List<Thread> threadList = new List<Thread>();
             string output = "<div class='text-center ui-layout-center ui-layout-pane ui-layout-pane-center'><div style ='display:inline-block' class='ui-selectable ui-droppable'>";
             if (nodes.Number.Equals(node))
             {
                 int childCount = 0;
                 if (nodes.Children.Count < 200)
                     childCount = nodes.Children.Count;
                 else
                 {
                     childCount = 200;
                 }
                 if(childCount < pCount * 2)
                 {
                     output += CreateNodeView(nodes, "node", left, top);
                     foreach(Node n2 in nodes.Children)
                     {
                         output += CreateNodeView(n2, "node-child");
                     }
                 }
                 else
                 {
                     int spread = (int)Math.Ceiling((double)childCount / (double)pCount);
                     output += CreateNodeView(nodes, "node",left,top);  //Parent(Node) Thread
                     for (int i = 0; i < pCount; i++)
                     {
                         int neg = 0;
                         if ((spread * (i + 1)) > childCount)
{
                             neg = childCount - (spread * (i + 1));
                         }
                         int start = (spread * i) ;
                         int rangeStart = (spread * i) + nodeStart;
                         bool showHigher = nodeStart != 0 ? true : false;
                         List<Node> NodesToProcess = nodes.Children.GetRange(rangeStart, spread + neg);
                         Thread threadJob = new Thread(() => CreateNodeChildViewsParallel(NodesToProcess, start, showHigher, childCount + nodeStart, nodeStart - childCount));
                         threadJob.Name = i.ToString();
                         threadJob.Start();
                         threadList.Add(threadJob);
                     }
                     foreach(Thread t in threadList)
                     {
                         t.Join();
                     }
                     cNodes.Sort((x, y) => x.Item1.CompareTo(y.Item1));
                     foreach(Tuple<int,string> tup in cNodes)
                     {
                         output += tup.Item2;
                     }
                 }
             }
             else
             {
                 GetParent(nodes, node);
                 string temp = "";
                 if (GotParent)
                 {
                     if (nodes.Number == Parent)
                     {
                         output += CreateNodeView(nodes, "node-parent");
                     }
                 }
                 bool found =false;
                 foreach (Node n2 in nodes.Children)
                 {
                     if (GotParent)
                     {
                         if (n2.Number == Parent)
{
                             output += CreateNodeView(n2, "node-parent");
                         }
                     }
                     temp += CheckChildren(n2, node,pCount,nodeStart,ref found);
                     if (found)
                         break;
                 }
                 if (!string.IsNullOrEmpty(temp))
                     output += temp;
             }
             output += "</div></div>";
             return output;
         }
CreateViewSingle()
string OSXJV.Classes.Output.CreateViewSingle (int node, int nodeStart = 0)
CreateView using a Single Thread
Parameters
node Index of node to start from
nodeStart Where to start the child nodes from
Returns
String of calculated HTML
Definition at line 107 of file Output.cs.
References OSXJV.Classes.Node.Children, and OSXJV.Classes.Node.Number.
         {
             string output = "<div class='text-center ui-layout-center ui-layout-pane ui-layout-pane-center'><div style ='display:inline-block' class='ui-selectable ui-droppable'>";
             if (nodes.Number.Equals(node))
             {
                 int count = 0;
                 output += CreateNodeView(nodes, "node");
                 foreach (Node n in nodes.Children)
                 {
                     if(nodeStart > 0)
                     {
                         if (count != nodeStart)
                             continue;
                     }
                     count++;
                     output += CreateNodeView(n, "node-child"); //Child(Nodes) Thread
                     if ((count-nodeStart) == 200)
                     {
                         output += CreateExtraNode("node-child",count);
                         break;
                     }
                 }
             }
             else
             {
                 GetParent(nodes, node);
                 string temp = "";
                 if (GotParent)
                 {
                     if (nodes.Number == Parent)
                     {
                         output += CreateNodeView(nodes, "node-parent");
                     }
                 }
                 foreach (Node n2 in nodes.Children)
                 {
                     if (GotParent)
                     {
                         if (n2.Number == Parent)
{
                             output += CreateNodeView(n2, "node-parent");
                         }
                     }
                     temp += CheckChildren(n2, node);
                 }
                 if (!string.IsNullOrEmpty(temp))
                     output += temp;
             }
             output += "</div></div>"; //Close out divs
             return output;
         }
GetParent()
void OSXJV.Classes.Output.GetParent (Node node, int number) private
Finds the parent node.
Parameters
node Node to search
number Node number to find
Definition at line 539 of file Output.cs.
References OSXJV.Classes.Node.Children, and OSXJV.Classes.Node.Number.
         {
             if(!CheckNodeNumber(node,number))
             {
                 foreach(Node n in node.Children)
                 {
                     if(CheckNodeNumber(n, number))
                     {
                         Parent = node.Number;
                         GotParent = true;
                     }
                     else
                     {
                         GetParent(n, number);
                     }
                 }
             }
         }
GridGetChidren()
JObject OSXJV.Classes.Output.GridGetChidren (Node n) private
Recursive function to get all the nodes data for the grid .
Parameters
n Child Node
Returns
JSON object
Definition at line 83 of file Output.cs.
References OSXJV.Classes.Node.Children, OSXJV.Classes.Node.Name, and OSXJV.Classes.Node.Number.
         {
             JObject child = new JObject();
             child.Add("id", n.Number);
             child.Add("text", n.Name);
             if (n.Children.Count > 0)
             {
                 JArray array = new JArray();
                 foreach(Node n2 in n.Children)
                 {
                     array.Add(GridGetChidren(n2));
                 }
                 child.Add("children", array);
             }
             return child;
         }
Member Data Documentation
cNodes
List<Tuple<int, string> > OSXJV.Classes.Output.cNodes = new List<Tuple<int, string>>() private
Used in Threading, list of calculated HTML strings.
Definition at line 36 of file Output.cs.
count
int OSXJV.Classes.Output.count = 0 static private
Used in Single Threaded operation to keep track of div id.
Definition at line 42 of file Output.cs.
GotParent
bool OSXJV.Classes.Output.GotParent = false private
Definition at line 26 of file Output.cs.
left
int OSXJV.Classes.Output.left = 100 private
Definition at line 16 of file Output.cs.
nodes
Node OSXJV.Classes.Output.nodes private
Definition at line 21 of file Output.cs.
Parent
int OSXJV.Classes.Output.Parent = 0 private
Parent of node when building output (Used when getting Node other than root).
Definition at line 31 of file Output.cs.
top
int OSXJV.Classes.Output.top = 130 private
Definition at line 16 of file Output.cs.
The documentation for this class was generated from the following file:
OSXJVClasses/Output.cs