Open Source XML & JSON Visualisation Software: OSXJV.Classes.CacheManager Class Reference
OSXJV.Classes.CacheManager Class Reference
Manages Saving an Retrieving Filesexi
Public Member Functions
string getFile (string ID)
Retrieve the file from caching
bool saveFile (string ID, string nodes)
Save the file to the local system for caching
Static Public Member Functions
static bool Setup (string path)
static CacheManager GetInstance ()
Get the single instance of the class
static void Close ()
Private Member Functions
CacheManager (string path)
Private Attributes
string path
Static Private Attributes
static CacheManager inst
Detailed Description
Manages Saving an Retrieving Filesexi
Definition at line 9 of file CacheManager.cs.
Constructor & Destructor Documentation
CacheManager()
OSXJV.Classes.CacheManager.CacheManager (string path) private
Definition at line 14 of file CacheManager.cs.
         {
             this.path = path;
         }
Member Function Documentation
Close()
static void OSXJV.Classes.CacheManager.Close () static
Definition at line 99 of file CacheManager.cs.
         {
             if (inst == null)
                 throw new Exception("CacheManager Already Closed");
             else
                 inst = null;
         }
getFile()
string OSXJV.Classes.CacheManager.getFile (string ID)
Retrieve the file from caching
Parameters
ID Unique ID of the file
Returns
Definition at line 51 of file CacheManager.cs.
Referenced by OSXJV.Server.OSXJVServer.HandleGet().
         {
             if (string.IsNullOrEmpty(ID))
                 throw new ArgumentException("ID cannot be null or empty");
             string filePath = path + "/" + ID.Replace("/","") + ".json";
             string output = "";
             using (StreamReader sr = new StreamReader(filePath))
             {
                 output = sr.ReadToEnd();
             }
             if (!string.IsNullOrEmpty(output))
                 return output;
             else
                 throw new Exception("Error Reading From File");
         }
GetInstance()
static CacheManager OSXJV.Classes.CacheManager.GetInstance () static
Get the single instance of the class
Returns
An instance of CacheManager
Definition at line 38 of file CacheManager.cs.
Referenced by OSXJV.Server.OSXJVServer.HandleGet(), OSXJV.Server.OSXJVServer.HandlePost(), and OSXJV.Server.OSXJVServer.SaveFile().
         {
             if (inst != null)
                 return inst;
             else
                 throw new Exception("CacheManger has not been setup");
         }
saveFile()
bool OSXJV.Classes.CacheManager.saveFile (string ID, string nodes)
Save the file to the local system for caching
Parameters
ID Unique ID of the file
nodes The document to be saved
Definition at line 75 of file CacheManager.cs.
Referenced by OSXJV.Server.OSXJVServer.HandlePost(), and OSXJV.Server.OSXJVServer.SaveFile().
         {
             if (string.IsNullOrEmpty(ID))
                 throw new ArgumentException("ID cannot be null or empty");
             if (string.IsNullOrEmpty(nodes))
                 throw new ArgumentException("Document cannot be null or empty");
             string filePath = path + "/" + ID + ".json";
             try
             {
                 using (StreamWriter sw = new StreamWriter(filePath))
                 {
                     sw.WriteLine(nodes);
                 }
             }
             catch
             {
                 throw new Exception("Failed to save file");
             }
             return true;
         }
Setup()
static bool OSXJV.Classes.CacheManager.Setup (string path) static
Parameters
path
Definition at line 23 of file CacheManager.cs.
Referenced by WebServer.Program.Main().
         {
             if (string.IsNullOrEmpty(path))
                 throw new ArgumentException("Path cannot be empty");
             if (!Directory.Exists(string.Format(@"{0}",path)))
                 throw new Exception("Path is not a valid cache directory");
             return (inst = new CacheManager(path)) != null ? true : false;
         }
Member Data Documentation
inst
CacheManager OSXJV.Classes.CacheManager.inst static private
Definition at line 11 of file CacheManager.cs.
path
string OSXJV.Classes.CacheManager.path private
Definition at line 12 of file CacheManager.cs.
The documentation for this class was generated from the following file:
OSXJVClasses/CacheManager.cs